"""add accession number to documents

Revision ID: 214f4cdf3396
Revises:
Create Date: 2026-09-23 14:09:38.862818

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "214f4cdf3396"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("accession_number", sa.String(length=32), nullable=True)
    )
    op.drop_constraint(op.f("uq_document_company_source"), "documents", type_="unique")
    op.create_index(
        op.f("ix_documents_accession_number"),
        "documents",
        ["accession_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_accession_number"), table_name="documents")
    op.create_unique_constraint(
        op.f("uq_document_company_source"),
        "documents",
        ["company_id", "source_url"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("documents", "accession_number")
    # ### end Alembic commands ###
