"""add document uniqueness constraints

Revision ID: 2ef0a22a46a9
Revises: 214f4cdf3396
Create Date: 2026-09-24 16:40:37.348577

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ef0a22a46a9"
down_revision: str | Sequence[str] | None = "214f4cdf3396"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_document_company_accession", "documents", ["company_id", "accession_number"]
    )
    op.create_unique_constraint(
        "uq_document_company_source", "documents", ["company_id", "source_url"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_document_company_source", "documents", type_="unique")
    op.drop_constraint("uq_document_company_accession", "documents", type_="unique")
    # ### end Alembic commands ###
